id: '21'
name: 21. Interact with Contract
summary: Interactions between contracts not only make the programs reusable on the
  blockchain, but also enrich the Ethereum ecosystem. Many `web3` Dapps rely on other
  contracts to work, for example `yield farm
level: intermediate
tags:
- solidity
- advanced
- wtfacademy
- call contract
steps:
- name: Interact with Contract
  path: step1
