id: '14'
name: 14. Abstract and Interface
summary: In this section, we will introduce the `abstract` and `interface` contracts
  in Solidity, using the interface of `ERC721` as an example. They are used to write
  contract templates and reduce code redund
level: beginner
tags:
- solidity
- basic
- wtfacademy
- abstract
- interface
steps:
- name: Abstract and Interface
  path: step1
