id: '11'
name: 11. constructor and modifier
summary: In this section, we will introduce `constructor` and `modifier` in Solidity,
  using an access control contract (`Ownable`) as an example.
level: beginner
tags:
- solidity
- basic
- wtfacademy
- constructor
- modifier
steps:
- name: constructor and modifier
  path: step1
