id: '44'
name: 44. Token Lock
summary: 'I have been relearning Solidity recently to solidify my understanding of
  the language and to create a "WTF Solidity Crash Course" for beginners (advanced
  programmers can find other tutorials). I will '
level: advanced
tags:
- solidity
- application
- ERC20
steps:
- name: Token Lock
  path: step1
