id: '31'
name: 31. ERC20
summary: 'In this lecture, we will introduce the ERC20 token standard on Ethereum
  and issue our test tokens. ERC20 is a token standard on Ethereum, which originated
  from the `EIP20` proposed by Vitalik Buterin '
level: intermediate
tags:
- solidity
- application
- wtfacademy
- ERC20
- OpenZeppelin
steps:
- name: ERC20
  path: step1
