id: '45'
name: 45. Time Lock
summary: I've been relearning Solidity recently to strengthen some details and write
  a "WTF Solidity Quick Start" for beginners (programming experts can find other tutorials),
  updated weekly with 1-3 lessons.
level: advanced
tags:
- solidity
- application
steps:
- name: Time Lock
  path: step1
