id: '24'
name: 24. Create
summary: On Ethereum, the user (Externally-owned account, `EOA`) can create smart
  contracts, and a smart contract can also create new smart contracts. The decentralized
  exchange `Uniswap` creates an infinite n
level: intermediate
tags:
- solidity
- advanced
- wtfacademy
- create contract
steps:
- name: Create
  path: step1
