id: '19'
name: 19. Receive ETH
summary: '`Solidity` has two special functions,  `receive()` and `fallback()`, they
  are primarily used in two circumstances.'
level: intermediate
tags:
- solidity
- advanced
- wtfacademy
- receive
- fallback
steps:
- name: Receive ETH
  path: step1
