id: '22'
name: 22. Call
summary: 'Previously in [20: Sending ETH](https://github.com/AmazingAng/WTF-Solidity/tree/main/Languages/en/20_SendETH_en)
  we talked about sending `ETH` with `call`, in this tutorial we will dive into that.'
level: intermediate
tags:
- solidity
- advanced
- wtfacademy
- call contract
- call
steps:
- name: Call
  path: step1
