id: '42'
name: 42. Payment Splitting
summary: I have been relearning solidity recently to solidify some of the details
  and to create a "WTF Solidity Crash Course" for beginners (advanced programmers
  can seek other tutorials). New lectures will be
level: advanced
tags:
- solidity
- application
steps:
- name: Payment Splitting
  path: step1
