id: '50'
name: 50. Multisignature Wallet
summary: I am currently relearning Solidity to solidify some of the details and create
  a "WTF Solidity Crash Course" for beginners (advanced programmers may want to find
  another tutorial). I will update 1-3 le
level: advanced
tags:
- Solidity
- call
- signature
- ABI encoding
steps:
- name: Multisignature Wallet
  path: step1
