id: 09
name: 9. Constant and Immutable
summary: 'In this section, we will introduce two keywords to restrict modifications
  to their state in Solidity: `constant` and `immutable`. If a state variable is declared
  with `constant` or `immutable`, its va'
level: beginner
tags:
- solidity
- tutorial
steps:
- name: Constant and Immutable
  path: step1
