id: 08
name: 8. Initial Value
summary: In Solidity, variables declared but not assigned have their initial/default
  values. In this tutorial, we will introduce the initial values of common variable
  types.
level: beginner
tags:
- solidity
- tutorial
steps:
- name: Initial Value
  path: step1
