id: '26'
name: 26. DeleteContract
summary: 'The `selfdestruct` operation is the only way to delete a smart contract
  and the remaining Ether stored at that address is sent to a designated target. The
  `selfdestruct` operation is designed to deal '
level: intermediate
tags:
- solidity
- advanced
- wtfacademy
- selfdestruct
- delete contract
steps:
- name: DeleteContract
  path: step1
