id: '36'
name: 36. Merkle Tree
summary: 'Recently, I have been reviewing solidity in order to consolidate some details
  and write a "WTF Solidity Beginner''s Guide" for novices (programming experts can
  find other tutorials). I will update 1-3 '
level: advanced
tags:
- solidity
- application
- wtfacademy
- ERC721
- Merkle Tree
steps:
- name: Merkle Tree
  path: step1
