id: '13'
name: 13. Inheritance
summary: In this section, we introduce `inheritance` in Solidity, including simple
  inheritance, multiple inheritance, and inheritance of modifiers and constructors.
level: beginner
tags:
- solidity
- basic
- wtfacademy
- inheritance
steps:
- name: Inheritance
  path: step1
