id: '49'
name: 49. UUPS
summary: I am currently relearning Solidity to solidify some of the details and create
  a "WTF Solidity Crash Course" for beginners (advanced programmers may want to find
  another tutorial). I will update 1-3 le
level: advanced
tags:
- solidity
- proxy
- OpenZeppelin
steps:
- name: UUPS
  path: step1
