id: S13
name: S13. Unchecked Low-Level Calls
summary: 'English translations by: [@to_22X](https://twitter.com/to_22X) ----- In
  this lesson, we will discuss the unchecked low-level calls in smart contracts. Failed
  low-level calls will not cause the transac'
level: advanced
tags:
- solidity
- security
- transfer/send/call
steps:
- name: Unchecked Low-Level Calls
  path: step1
