id: '07'
name: 7. Mapping
summary: 'In this section, we will introduce the hash table in Solidity: `mapping`
  type. With `mapping` type, people can query the corresponding `Value` by using a
  `Key`. For example, a person''s wallet address '
level: beginner
tags:
- solidity
- tutorial
steps:
- name: Mapping
  path: step1
