id: S08
name: S08. Contract Check Bypassing
summary: 'English translations by: [@to_22X](https://twitter.com/to_22X) ----- In
  this lesson, we will discuss contract length checks bypassing and introduce how
  to prevent it.'
level: advanced
tags:
- solidity
- security
- constructor
steps:
- name: Contract Check Bypassing
  path: step1
