id: '40'
name: 40. ERC1155
summary: I am currently relearning Solidity to reinforce my knowledge of its intricacies
  and write a "WTF Solidity Crash Course" for beginners (expert programmers may seek
  out other tutorials). Updates will be
level: advanced
tags:
- solidity
- application
- wtfacademy
- ERC1155
steps:
- name: ERC1155
  path: step1
