id: '43'
name: 43. Linear Release
summary: I am currently re-learning Solidity to consolidate my understanding of the
  details and to create a "Simplified Solidity for Beginners" guide for newbies (programming
  experts can find other tutorials).
level: advanced
tags:
- solidity
- application
- ERC20
steps:
- name: Linear Release
  path: step1
