id: '15'
name: 15. Errors
summary: 'In this chapter, we will introduce three ways to throw exceptions in solidity:
  `error`, `require`, and `assert`.'
level: beginner
tags:
- solidity
- advanced
- wtfacademy
- error
- revert/assert/require
steps:
- name: Errors
  path: step1
