id: 56-decentralized-exchange
name: 56. Decentralized Exchange
summary: Build a decentralized exchange (DEX) from scratch, learning about automated market makers (AMM), liquidity pools, and token swapping mechanisms.
level: 2
tags:
- solidity
- erc20
- Defi
steps:
- name: Decentralized Exchange
  path: step1
