id: '06'
name: 6. Array & Struct
summary: 'In this lecture, we will introduce two important variable types in Solidity:
  `array` and `struct`. An `array` is a variable type commonly used in Solidity to
  store a set of data (integers, bytes, addr'
level: beginner
tags:
- solidity
- tutorial
steps:
- name: Array & Struct
  path: step1
