id: '47'
name: 47. Upgradeable Contract
summary: 'I have recently been revising Solidity to consolidate the details, and am
  writing a "WTF Simplified Introduction to Solidity" for beginners to use (programming
  experts can find other tutorials), with '
level: advanced
tags:
- solidity
- proxy
- OpenZeppelin
steps:
- name: Upgradeable Contract
  path: step1
