id: '29'
name: 29. Function Selector
summary: When we call a smart contract, we essentially send a `calldata` to the target
  contract. After sending a transaction in the remix, we can see in the details that
  `input` is the `calldata` of this trans
level: intermediate
tags:
- solidity
- advanced
- wtfacademy
- selector
steps:
- name: Function Selector
  path: step1
