id: s01-reentrancy-attack
name: S01. Reentrancy Attack
summary: Learn about the most common type of smart contract attack - reentrancy attacks. Understand how they work, their historical impact on Ethereum, and how to prevent them in your contracts.
level: 2
tags:
- solidity
- security
- fallback
- modifier
steps:
- name: Reentrancy Attack
  path: step1
