id: '20'
name: 20. Sending ETH
summary: 'There are three ways of sending `ETH` in `Solidity`: `transfer()`, `send()`
  and `call()`, in which `call()` is recommended.'
level: intermediate
tags:
- solidity
- advanced
- wtfacademy
- transfer/send/call
steps:
- name: Sending ETH
  path: step1
