id: S05
name: S05. Integer Overflow
summary: 'English translations by: [@to_22X](https://twitter.com/to_22X) ----- In
  this lesson, we will introduce the integer overflow vulnerability (Arithmetic Over/Under
  Flows). This is a relatively common vul'
level: advanced
tags:
- solidity
- security
steps:
- name: Integer Overflow
  path: step1
